Traceback (most recent call last):
  File "/home/masumoto/anaconda3/envs/py36_tf114/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/masumoto/anaconda3/envs/py36_tf114/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/masumoto/coper/CoPER_ConvE/qa_cpg/run_cpg.py", line 51, in <module>
    if use_cpg:
NameError: name 'use_cpg' is not defined
